---
title: "Transformations"
author: "Shubh Tandon"
date: "2025-03-06"
output: html_document
---

TL'DR
The first few chunks (lines 12-172) is for transformation of the variables.
After that is me testing lm models.
The last two chunks is the final model labeled final model.


```{r}
death <- read_csv("~/Downloads/heart_failure_clinical_records_dataset.csv")

#Box-cox for age with no trandsformation and lamda value
fit.age <- lm(age~ejection_fraction+ creatinine_phosphokinase+platelets+serum_creatinine+serum_sodium, data=death)
bc <- boxcox(fit.age)
title(main = "95% CI for the Box-Cox transform.")
(lambda.hat <- bc$x[which.max(bc$y)])
```

```{r}
#since lambda is close to 0, we must log age,
fit.age_log <- lm(log(age)~ejection_fraction+ creatinine_phosphokinase+ ejection_fraction+platelets+serum_creatinine+serum_sodium, data=death)
summary(fit.age_log)

#log boxCox should be 1 which is good
boxCox(fit.age,family="yjPower")
boxCox(fit.age_log,family="yjPower")

```

```{r}
#check improvement of age
par(mfrow = c(1, 2))

hist(death$age, breaks = 30, main = "Histogram of Age", xlab = "Age", probability = TRUE)
lines(density(death$age), lwd = 2)

hist(log(death$age), breaks = 30, main = "Histogram of log(Age)", xlab = "log(Age)", probability = TRUE)
lines(density(log(death$age)), lwd = 2)


```


```{r}
#check indepedent variables
par(mfrow = c(2, 3))

continuous_vars <- c("ejection_fraction", "creatinine_phosphokinase", "platelets", "serum_creatinine", "serum_sodium")

for (var in continuous_vars) {
  hist(death[[var]], breaks = 30, main = paste("Histogram of", var), xlab = var, probability = TRUE)
  lines(density(death[[var]]), col = "red", lwd = 2)
}


```


```{r}
#check scatter plots of log(age) vs independent continous variables
par(mfrow = c(2, 3))

for (var in continuous_vars) {
  plot(death[[var]], log(death$age), main = paste("log(Age) vs", var), xlab = var, ylab = "log(Age)", pch = 19, col = "blue")
  abline(lm(log(age) ~ death[[var]], data = death), col = "red", lwd = 2)
}

```
```{r}

#check residuals for log(age) vs independent continuous variables

par(mfrow = c(2, 3))

for (var in continuous_vars) {
  plot(death[[var]], residuals(fit.age_log), 
       main = paste("Residuals vs", var), 
       xlab = var, 
       ylab = "Residuals", 
       pch = 19, col = "blue")
  abline(h = 0, col = "red", lwd = 2)
}
```

```{r}
#log creatinine_phosphokinase and serum_creatinine, then see residual plots
death$log_creatinine_phosphokinase <- log(death$creatinine_phosphokinase)
death$log_serum_creatinine <- log(death$serum_creatinine)

fit_transformed <- lm(log(age) ~ ejection_fraction + log_creatinine_phosphokinase + platelets + log_serum_creatinine + serum_sodium, data = death)

par(mfrow = c(2, 3))
trans_continuous_vars <- c("ejection_fraction", "log_creatinine_phosphokinase", "platelets", "log_serum_creatinine", "serum_sodium")

for (var in trans_continuous_vars) {
  plot(death[[var]], residuals(fit_transformed), 
       main = paste("Residuals vs", var), 
       xlab = var, 
       ylab = "Residuals", 
       pch = 19, col = "blue")
  abline(h = 0, col = "red", lwd = 2)
}


```
```{r}
#log creatinine_phosphokinase and serum_creatinine, then see scatter plots
par(mfrow = c(2, 3))
for (var in trans_continuous_vars) {
  plot(death[[var]], log(death$age), main = paste("log(Age) vs", var), xlab = var, ylab = "log(Age)", pch = 19, col = "blue")
  abline(lm(log(age) ~ death[[var]], data = death), col = "red", lwd = 2)
}
```

```{r}
#final qq and residual transformed
par(mfrow = c(1, 2))

qqnorm(residuals(fit_transformed), main = "QQ Plot of Residuals")
qqline(residuals(fit_transformed), col = "red", lwd = 2)

plot(fitted(fit_transformed), residuals(fit_transformed), 
     main = "Residuals vs. Fitted Values", 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     pch = 19, col = "blue")
abline(h = 0, col = "red", lwd = 2)

par(mfrow = c(1, 1))

```

```{r}
#pre transformations qq and residual

fit.age <- lm(age ~ ejection_fraction + creatinine_phosphokinase + platelets + serum_creatinine + serum_sodium, data = death)

par(mfrow = c(1, 2))

qqnorm(residuals(fit.age), main = "QQ Plot of Residuals")
qqline(residuals(fit.age), col = "red", lwd = 2)

plot(fitted(fit.age), residuals(fit.age), 
     main = "Residuals vs. Fitted Values", 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     pch = 19, col = "blue")
abline(h = 0, col = "red", lwd = 2)

par(mfrow = c(1, 1))
```

```{r}
death_transformed <- death

death_transformed$log_age <- log(death$age)  # Replace age with log(age)
death_transformed$log_creatinine_phosphokinase <- log(death$creatinine_phosphokinase)
death_transformed$log_serum_creatinine <- log(death$serum_creatinine)

death_transformed$age <- NULL
death_transformed$creatinine_phosphokinase <- NULL
death_transformed$serum_creatinine <- NULL

categorical_vars <- c("anaemia", "diabetes", "high_blood_pressure", "sex", "smoking", "DEATH_EVENT")

death_transformed[categorical_vars] <- lapply(death_transformed[categorical_vars], as.factor)


```

```{r}
age_final_model <- lm(log_age ~ (.-DEATH_EVENT-time), data = death_transformed)
summary(age_final_model)
```


```{r}
reduced_model <- lm(log_age ~ anaemia + ejection_fraction + high_blood_pressure + 
           sex + log_serum_creatinine, data = death_transformed)
summary(reduced_model)

```
```{r}


best_model <- step(age_final_model, direction = "backward", test = "F")
```

```{r}
reduced_model <- lm(log_age ~ anaemia + ejection_fraction + high_blood_pressure + 
           sex + log_serum_creatinine, data = death_transformed)
anova(reduced_model, age_final_model)
```

```{r}
summary(reduced_model)
```

```{r}
reduced_model <- lm(log_age ~ anaemia + ejection_fraction +high_blood_pressure +log_serum_creatinine +
           sex , data = death_transformed)
summary(reduced_model)
```



```{r}
reduced_model_int <- lm(log_age ~ anaemia * ejection_fraction *high_blood_pressure *log_serum_creatinine *
           sex , data = death_transformed)
summary(reduced_model_int)
```
```{r}
full_model <- lm(log_age ~ anaemia * ejection_fraction * high_blood_pressure * log_serum_creatinine * sex, 
                 data = death_transformed)

reduced_model <- step(full_model, direction = "backward", test = "F")

anova(full_model, reduced_model)


```

```{r}
# Fit the reduced model based on ANOVA results
reduced_model_int <- lm(log_age ~ anaemia + ejection_fraction + high_blood_pressure + 
                        log_serum_creatinine + sex + 
                        anaemia:ejection_fraction + anaemia:high_blood_pressure + 
                        ejection_fraction:high_blood_pressure + anaemia:log_serum_creatinine + 
                        ejection_fraction:log_serum_creatinine + anaemia:sex + 
                        ejection_fraction:sex + high_blood_pressure:sex + 
                        anaemia:ejection_fraction:high_blood_pressure + 
                        anaemia:ejection_fraction:log_serum_creatinine + 
                        anaemia:ejection_fraction:sex + anaemia:high_blood_pressure:sex + 
                        ejection_fraction:high_blood_pressure:sex + 
                        anaemia:ejection_fraction:high_blood_pressure:sex, 
                        data = death_transformed)

# Summarize the model
summary(reduced_model_int)

```



```{r}
fitted_values <- fitted(reduced_model_int)
actual_values <- death_transformed$log_age

plot(fitted_values, actual_values, 
     xlab = "Fitted Values", ylab = "Actual Values", 
     main = "Predicted vs. Actual Values",
     col = "blue", pch = 16)
abline(0, 1, col = "red", lwd = 2)  # Add y = x line for reference

```
```{r}
fitted_values <- exp(fitted(reduced_model_int))
actual_values <- exp(death_transformed$log_age) 

plot(fitted_values, actual_values, 
     xlab = "Predicted Age", ylab = "Actual Age", 
     main = "Predicted vs. Actual Age",
     col = "blue", pch = 16)
abline(0, 1, col = "red", lwd = 2) 
```
```{r}
reduced_model_int <- lm(log_age ~ anaemia+ ejection_fraction +high_blood_pressure +log_serum_creatinine +
           sex , data = death_transformed)
summary(reduced_model_int)
```
```{r}
par(mfrow = c(2, 2))

plot(death_transformed$ejection_fraction, resid(reduced_model_int), 
     main = "Residuals vs. Ejection Fraction", xlab = "Ejection Fraction", ylab = "Residuals", 
     col = "blue", pch = 16)
abline(h = 0, col = "red")

plot(death_transformed$log_serum_creatinine, resid(reduced_model_int), 
     main = "Residuals vs. Log Serum Creatinine", xlab = "Log Serum Creatinine", ylab = "Residuals", 
     col = "blue", pch = 16)
abline(h = 0, col = "red")

```
```{r}
poly_model <- lm(log_age ~ anaemia * (ejection_fraction) *
                 high_blood_pressure * poly(log_serum_creatinine, 2) * sex, 
                 data = death_transformed)

summary(poly_model)

```

```{r}
reduced_model <- step(poly_model, direction = "backward", test = "F")

```

```{r}
final_model <- lm(log_age ~ anaemia * high_blood_pressure * sex + 
                  ejection_fraction * high_blood_pressure * poly(log_serum_creatinine, 2) + 
                  ejection_fraction * high_blood_pressure * sex + 
                  anaemia * ejection_fraction * sex, 
                  data = death_transformed)

summary(final_model)

```
```{r}
fitted_values <- exp(fitted(final_model))
actual_values <- exp(death_transformed$log_age) 

plot(fitted_values, actual_values, 
     xlab = "Predicted Age", ylab = "Actual Age", 
     main = "Predicted vs. Actual Age",
     col = "blue", pch = 16)
abline(0, 1, col = "red", lwd = 2) 

```



