---
title: "Kidney"
author: "Shubh Tandon"
date: "2025-03-06"
output: html_document
---
```{r}
death <- read_csv("~/Downloads/heart_failure_clinical_records_dataset.csv")

#Box-cox for serum_creatinine with no trandsformation and lamda value
fit.sc <- lm(serum_creatinine~age + ejection_fraction + creatinine_phosphokinase + platelets + serum_sodium, data=death)
bc <- boxcox(fit.sc)
title(main = "95% CI for the Box-Cox transform.")
(lambda.hat <- bc$x[which.max(bc$y)])
```


```{r}

```

```{r}
#since lambda is close to -1, we must 1/serum_creatinine,

fit.1_sc <- lm(1/serum_creatinine~age+ejection_fraction+ creatinine_phosphokinase+ ejection_fraction+platelets+serum_sodium, data=death)
summary(fit.1_sc)

```
```{r}
#check improvement of sc
par(mfrow = c(1, 2))

hist(death$serum_creatinine, breaks = 30, main = "Histogram of Age", xlab = "Age", probability = TRUE)
lines(density(death$serum_creatinine), lwd = 2)

hist(1/(death$serum_creatinine), breaks = 30, main = "Histogram of log(Age)", xlab = "log(Age)", probability = TRUE)
lines(density(1/(death$serum_creatinine)), lwd = 2)
```

```{r}
#check indepedent variables
par(mfrow = c(2, 3))

continuous_vars <- c("ejection_fraction", "creatinine_phosphokinase", "platelets", "age", "serum_sodium")

for (var in continuous_vars) {
  hist(death[[var]], breaks = 30, main = paste("Histogram of", var), xlab = var, probability = TRUE)
  lines(density(death[[var]]), col = "red", lwd = 2)
}
```
```{r}
#check scatter plots of 1/sc vs independent continous variables
par(mfrow = c(2, 3))

for (var in continuous_vars) {
  plot(death[[var]], 1/(death$serum_creatinine), main = paste("1/sc vs", var), xlab = var, ylab = "1/serum_creatinine", pch = 19, col = "blue")
  abline(lm(1/(death$serum_creatinine) ~ death[[var]], data = death), col = "red", lwd = 2)
}
```
```{r}
#check residuals for 1/sc vs independent continuous variables

par(mfrow = c(2, 3))

for (var in continuous_vars) {
  plot(death[[var]], residuals(fit.1_sc), 
       main = paste("Residuals vs", var), 
       xlab = var, 
       ylab = "Residuals", 
       pch = 19, col = "blue")
  abline(h = 0, col = "red", lwd = 2)
}
```
```{r}
#log creatinine_phosphokinase and platelets, then see residual plots
death$log_creatinine_phosphokinase <- log(death$creatinine_phosphokinase)
death$log_platelets <- log(death$platelets)

fit_transformed <- lm(1/serum_creatinine ~ ejection_fraction + log_creatinine_phosphokinase + log_platelets + serum_sodium, data = death)

par(mfrow = c(2, 3))
trans_continuous_vars <- c("ejection_fraction", "log_creatinine_phosphokinase", "log_platelets", "age", "serum_sodium")

for (var in trans_continuous_vars) {
  plot(death[[var]], residuals(fit_transformed), 
       main = paste("Residuals vs", var), 
       xlab = var, 
       ylab = "Residuals", 
       pch = 19, col = "blue")
  abline(h = 0, col = "red", lwd = 2)
}

```

```{r}
#transformed scatter plots
par(mfrow = c(2, 3))
for (var in trans_continuous_vars) {
  plot(death[[var]], 1/(death$serum_creatinine), main = paste("1/sc vs", var), xlab = var, ylab = "1/sc", pch = 19, col = "blue")
  abline(lm(1/(death$serum_creatinine) ~ death[[var]], data = death), col = "red", lwd = 2)
}
```
```{r}
#final qq and residual transformed
par(mfrow = c(1, 2))

qqnorm(residuals(fit_transformed), main = "QQ Plot of Residuals")
qqline(residuals(fit_transformed), col = "red", lwd = 2)

plot(fitted(fit_transformed), residuals(fit_transformed), 
     main = "Residuals vs. Fitted Values", 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     pch = 19, col = "blue")
abline(h = 0, col = "red", lwd = 2)

par(mfrow = c(1, 1))

```
```{r}
#pre transformations qq and residual


par(mfrow = c(1, 2))

qqnorm(residuals(fit.sc), main = "QQ Plot of Residuals")
qqline(residuals(fit.sc), col = "red", lwd = 2)

plot(fitted(fit.sc), residuals(fit.sc), 
     main = "Residuals vs. Fitted Values", 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     pch = 19, col = "blue")
abline(h = 0, col = "red", lwd = 2)

par(mfrow = c(1, 1))

```

```{r}
death_transformed <- death

death_transformed$inv_serum_creatinine <- 1/(death$serum_creatinine)  # Replace age with log(age)
death_transformed$log_creatinine_phosphokinase <- log(death$creatinine_phosphokinase)
death_transformed$log_platelets <- log(death$platelets)

death_transformed$serum_creatinine <- NULL
death_transformed$creatinine_phosphokinase <- NULL
death_transformed$platelets <- NULL

categorical_vars <- c("anaemia", "diabetes", "high_blood_pressure", "sex", "smoking", "DEATH_EVENT")

death_transformed[categorical_vars] <- lapply(death_transformed[categorical_vars], as.factor)

```

```{r}
sc_first_try <- lm(inv_serum_creatinine ~ (.-DEATH_EVENT-time), data = death_transformed)
summary(sc_first_try)
```
```{r}
sc_red_try <- lm(inv_serum_creatinine ~ age * anaemia * diabetes * ejection_fraction * high_blood_pressure *serum_sodium*sex*smoking*log_creatinine_phosphokinase*log_platelets, data = death_transformed)
summary(sc_red_try)
```

```{r}
sc_reduce<- step(sc_first_try, direction = "backward", test = "F")
summary(sc_reduce)
```
```{r}
sc_reduce_try <- lm(inv_serum_creatinine ~ age * ejection_fraction * high_blood_pressure *serum_sodium, data = death_transformed)
summary(sc_reduce_try)
```
```{r}
sc_reduce_try <- lm(inv_serum_creatinine ~ age * poly(ejection_fraction,2) * high_blood_pressure *poly(serum_sodium,2), data = death_transformed)
summary(sc_reduce_try)
```
```{r}
sc_reduce<- step(sc_reduce_try, direction = "backward", test = "F")
```
```{r}
sc_reduce_try <- lm(inv_serum_creatinine ~ age * poly(ejection_fraction,2) * high_blood_pressure *poly(serum_sodium,1), data = death_transformed)
summary(sc_reduce_try)
```

```{r}
sc_reduce_try <- lm(inv_serum_creatinine ~ poly(ejection_fraction,2) * poly(serum_sodium,2)*age*high_blood_pressure , data = death_transformed)
summary(sc_reduce_try)
```


```{r}
sc_reduce<- step(sc_reduce_try, direction = "backward", test = "F")

```
```{r}
final_model <- lm( inv_serum_creatinine ~ poly(ejection_fraction, 2) + 
                       poly(serum_sodium, 2) + 
                       age + 
                       high_blood_pressure + 
                       poly(ejection_fraction, 2):poly(serum_sodium, 2) + 
                       poly(ejection_fraction, 2):age + 
                       poly(ejection_fraction, 2):high_blood_pressure + 
                       age:high_blood_pressure + 
                       poly(ejection_fraction, 2):age:high_blood_pressure, data = death_transformed)


summary(final_model)
```
```{r}
fitted_values <- fitted(final_model)

actual_values <- death_transformed$inv_serum_creatinine

plot(fitted_values, actual_values, 
     xlab = "Predicted inv(Serum Creatinine)", 
     ylab = "Actual inv(Serum Creatinine)", 
     main = "Predicted vs. Actual inv(Serum Creatinine)",
     col = "blue", pch = 16)

# Add a reference line (y = x) for ideal predictions
abline(0, 1, col = "red", lwd = 2)
```
```{r}
par(mfrow = c(1, 2))

qqnorm(residuals(final_model), main = "QQ Plot of Residuals")
qqline(residuals(final_model), col = "red", lwd = 2)

plot(fitted(final_model), residuals(final_model), 
     main = "Residuals vs. Fitted Values", 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     pch = 19, col = "blue")
abline(h = 0, col = "red", lwd = 2)

par(mfrow = c(1, 1))
```



